In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a.shape)

(3,)


In [5]:
print(a[0],a[1],a[2])

1 2 3


In [6]:
a[0]=5

In [7]:
print(a)

[5 2 3]


In [8]:
b=np.array([[1,2,3],[4,5,6]])

In [9]:
print(b.shape)

(2, 3)


In [10]:
print(b[0,0],b[0,1],b[1,0])

1 2 4


In [11]:
a=np.zeros((2,2))

In [12]:
print(a)

[[0. 0.]
 [0. 0.]]


In [13]:
b=np.ones((1,2))

In [14]:
print(b)

[[1. 1.]]


In [15]:
c=np.full((2,2),7)

In [16]:
print(c)

[[7 7]
 [7 7]]


In [17]:
c=np.full((3,4),8)

In [18]:
print(c)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [19]:
d=np.eye(2)

In [20]:
print(d)

[[1. 0.]
 [0. 1.]]


In [21]:
e=np.random.random((2,3))

In [22]:
print(e)

[[0.08185398 0.25817027 0.70843193]
 [0.75966966 0.92193907 0.44331563]]


In [23]:
a=np.array(([[1,2,3,4],[5,6,7,8],[9,10,11,12]]))

In [24]:
b=a[:2,1:3]

In [25]:
print(b)

[[2 3]
 [6 7]]


In [26]:
b[0,0]=43

In [27]:
print(a)

[[ 1 43  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
a[:2,1:]

array([[43,  3,  4],
       [ 6,  7,  8]])

In [29]:
a[1:2,2:]

array([[7, 8]])

In [30]:
a[1:3,2:]

array([[ 7,  8],
       [11, 12]])

In [31]:
arr=np.arrange(1,11)

AttributeError: module 'numpy' has no attribute 'arrange'

In [32]:
arr=np.arange(1,11)

In [33]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [35]:
boolar=arr>5

In [36]:
boolar

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [37]:
arr[boolar]

array([ 6,  7,  8,  9, 10])

In [38]:
arr2d=np.arange(50).reshape(5,10)

In [39]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [40]:
x=np.array([1,2])

In [41]:
print(x.dtype)

int32


In [42]:
x=np.array([1,2],dtype=np.int64)

In [43]:
print(x.dtype)

int64


In [44]:
x=np.array([[1,2],[3,4]])

In [45]:
y=np.array([[5,6],[7,8]])

In [46]:
print(x+y)

[[ 6  8]
 [10 12]]


In [47]:
print np.add(x,y)

SyntaxError: invalid syntax (<ipython-input-47-6cec52d92fc7>, line 1)

In [48]:
print(np.add(x,y))

[[ 6  8]
 [10 12]]


In [49]:
x=np.array([[1,2],[3,4]])

In [50]:
y=np.array([[5,6],[7,8]])

In [51]:
print(x.dot(y))

[[19 22]
 [43 50]]


In [52]:
x=np.array([[1,2],[3,4]])

In [53]:
print(np.sum(x))

10
